"""Initial migration with all CMS models (fixed card index)

Revision ID: 94b0b448cb8f
Revises:
Create Date: 2025-08-16 12:54:31.035258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b0b448cb8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('card_index', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('subtitle_ru', sa.Text(), nullable=True),
    sa.Column('subtitle_en', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=2048), nullable=True),
    sa.Column('open_in_new_tab', sa.Boolean(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'animation', name='cardmediatypeenum'), nullable=False),
    sa.Column('image_path', sa.String(length=1024), nullable=True),
    sa.Column('animation_mode', sa.Enum('css_snippet', 'css_file', 'json_config', name='cardanimationmodeenum'), nullable=True),
    sa.Column('animation_payload', sa.Text(), nullable=True),
    sa.Column('animation_file_path', sa.String(length=1024), nullable=True),
    sa.Column('alt_ru', sa.String(length=255), nullable=True),
    sa.Column('alt_en', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='statusenum'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('card_index >= 0 AND card_index <= 4', name='chk_card_index'),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
